name: blot
services:
  node-app:
    image: blot
    # even though the os.cpu stats don't reflect this, it does seem capable
    # of throttling the performance of the node.js service, somehow! 
    # useful to simulate real-life server resources
    cpus: 0.75
    build:
      context: ../../
      dockerfile: Dockerfile
      target: dev   # This line specifies which stage to build
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - ../../.env
    environment:
      - BLOT_HOST=${BLOT_HOST}
      - BLOT_REDIS_HOST=redis
      - CONTAINER_NAME=blot-container-green
    volumes:
      - ../../data:/usr/src/app/data
      - ../../.git:/usr/src/app/.git
      - ../../app:/usr/src/app/app
      - ../../tests:/usr/src/app/tests
      - ../../notes:/usr/src/app/notes
      - ../../scripts:/usr/src/app/scripts
      - ../../TODO:/usr/src/app/TODO
      - ../../config:/usr/src/app/config
    command: npx --node-options="--max-old-space-size=750 --trace-deprecation" nodemon /usr/src/app/app/index.js --watch /usr/src/app/app -e js,html,css --ignore /usr/src/app/app/documentation/data --ignore /usr/src/app/app/documentation/output --ignore /usr/src/app/app/views --ignore /usr/src/app/app/views-built  --ignore /usr/src/app/app/clients/*/views --ignore /usr/src/app/app/templates/folders --ignore /usr/src/app/app/templates/source

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379" # Expose Redis port 6379 to host so we can run scripts if needed
    volumes:
      - "../../data:/data"

  nginx:
    build:
      context: ../../config/openresty
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../config/openresty/development_server.conf:/etc/nginx/nginx.conf:ro
      - ../../config/openresty/init.sh:/etc/nginx/init.sh:ro
      - ../../data/ssl:/etc/ssl:ro
    depends_on:
      - node-app
    command: /bin/sh -c "sh /etc/nginx/init.sh"
